### ISSUE TITLE
Reference allele value for Number=R VCF INFO attributes

### ISSUE THREAD

**Issue by heuermh** [bigdatagenomics/bdg-formats#118]
The documentation for `VariantAttribute` fields states that Number=R VCF INFO attribute values are split for multi-allelic sites
```
  /**
   Total read depth, VCF INFO reserved key AD, Number=R, split for multi-allelic
   sites.
   */
  union { null, int } readDepth = null;

  /**
   Forward strand read depth, VCF INFO reserved key ADF, Number=R, split for
   multi-allelic sites.
   */
  union { null, int } forwardReadDepth = null;

  /**
   Reverse strand read depth, VCF INFO reserved key ADR, Number=R, split for
   multi-allelic sites.
   */
  union { null, int } reverseReadDepth = null;

...

  /**
   Additional variant attributes that do not fit into the standard fields above.
   The values are stored as strings, even for flag, integer, and float types. VCF
   INFO key values with Number=., Number=0, Number=1, and Number=[n] are shared across
   all alternate alleles in the same VCF record. VCF INFO key values with Number=A and
   Number=R are split for multi-allelic sites.
   */
  map<string> attributes = {};
```

When converting VCF records to `VariantAnnotation` records, we [assume that the first index of the array is the reference allele value](https://github.com/samtools/hts-specs/issues/154), and use the alternate allele index to extract the value for the alternate allele.

```
##INFO=<ID=MY,Number=R,Type=Integer,Description="My Number=R attribute">
1  1024  .  G  A,T  .  PASS  MY=10,20,30
```
```
{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "A", "annotation":{"attributes": "MY=20"}}

{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "T", "annotation":{"attributes": "MY=30"}}
```

When converting from `VariantAnnotation` back to VCF records, we no longer have access to the reference allele value.  I can think of at least four ways to handle this:

1. Add a default value based on the Type

```
1  1024  .  G  A  .  PASS  MY=-1,20
1  1024  .  G  T  .  PASS  MY=-1,30
```

2. Add the missing value

```
1  1024  .  G  A  .  PASS  MY=.,20
1  1024  .  G  T  .  PASS  MY=.,30
```

3. Write as Number=R with the wrong cardinality

```
1  1024  .  G  A  .  PASS  MY=20
1  1024  .  G  T  .  PASS  MY=30
```

4. Create `Variant` and `VariantAnnotation` records for the reference allele when splitting multi-allelic sites

```
{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "<*>", "annotation":{"attributes": "MY=10"}}

{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "A", "annotation":{"attributes": "MY=20"}}

{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "T", "annotation":{"attributes": "MY=30"}}
```

```
1  1024  .  G  <*>  .  PASS  MY=10
1  1024  .  G  A  .  PASS  MY=20
1  1024  .  G  T  .  PASS  MY=30
```

<br/>
<br/>

For the Number=R VCF INFO attribute values that map to fields (currently AD, ADF, ADR) we have a couple more options:

```
1  1024  .  G  A,T  .  PASS  AD=10,20,30
```

5. Use `array<int>` for the field type with cardinality 2

```
  array<int> readDepth = [];
  array<int> forwardReadDepth = [];
  array<int> reverseReadDepth = [];
```
```
{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "A", "annotation":{"readDepth": 10,20}}

{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "T", "annotation":{"readDepth": 10,30}}
```
```
1  1024  .  G  A  .  PASS  AD=10,20
1  1024  .  G  T  .  PASS  AD=10,30
```

6. Add new reference value fields

```
  union { null, int } readDepth = null;
  union { null, int } forwardReadDepth = null;
  union { null, int } reverseReadDepth = null;

  union { null, int } referenceReadDepth = null;
  union { null, int } referenceForwardReadDepth = null;
  union { null, int } referenceReverseReadDepth = null;
```
```
{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "A", "annotation":{"readDepth": 20, "referenceReadDepth": 10}}

{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "A", "annotation":{"readDepth": 30, "referenceReadDepth": 10}}
```
```
1  1024  .  G  A  .  PASS  AD=10,20
1  1024  .  G  T  .  PASS  AD=10,30
```

<br/>
<br/>

New option, with 5 above, as proposed below

```
##INFO=<ID=MY,Number=R,Type=Integer,Description="My Number=R attribute">
1  1024  .  G  A,T  .  PASS  AD=5,15,25;MY=10,20,30
```
```
{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "A", "annotation":{"readDepth": [5,15], "attributes": "MY=10,20"}}

{"contigName": "1", "start": 1024, "referenceAllele": "G",
 "alternateAllele": "T", "annotation":{"readDepth": [5,25], "attributes": "MY=10,30"}}
```
```
1  1024  .  G  A  .  PASS  AD=5,15;MY=10,20
1  1024  .  G  T  .  PASS  AD=5,25;MY=10,30
```

**Comment by heuermh** [comment]
@fnothaft @jpdna I believe this one is a blocker for the next point release (0.10.1 or 0.11.0, however we decide) as I can't finish the implementation in https://github.com/bigdatagenomics/adam/pull/1288 without a decision on this.

**Comment by jpdna** [comment]
> Add new reference value fields
I like the approach in your 6. above of adding new explicitly named `ref` prefixed fields.

If the decision was made to do that, then what further problems still remain?

**Comment by heuermh** [comment]
Option 6 only helps for the specific case of Number=R VCF INFO attribute values that map to fields.  We'd still need something for generic Number=R VCF INFO values in `VariantAnnotation.attributes` (1-4).

Then after many years dealing with corporate DBAs and other such naming standard b.s., I no longer abbreviate  in field, method, or class names, so it'd be `reference*`.  :)

**Comment by jpdna** [comment]
How about we have a rule that for all Number=R  attribute map "fields" that the the String that is the the value must itself by a comma delimited list with exactly two fields (post splitting), ref and alt

**Comment by heuermh** [comment]
I'd go for that if we also went with option 5 for AD,ADF,ADR.

**Comment by jpdna** [comment]
Yeah I see why you'd want option 5 over 6 then for consistency, that's be fine with me.

We could also make attributes  a map of array<String> where often the array would be length one (rather than have comma delimited strings in some cases), but I am not sure if I like the potential overhead of that nesting.   Anyway, that attributes map representation decision would be easy to change in future though if we changed mind.
