### ISSUE TITLE
Variant should store whether it has a non-ref model

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/bdg-formats#124]
Was working on a fix for https://github.com/bigdatagenomics/adam/issues/1381, and the long and short of things is that we should add a flag to note that a variant also has a non-ref (gVCF) model attached. This makes the fix to said issue much easier, and also makes this more explicit (right now, we imply it with a null alt allele).

**Comment by heuermh** [comment]
Fixed in https://github.com/bigdatagenomics/adam/issues/1381
