### ISSUE TITLE
NucleotideContigFragment uses `contig` instead of `contigName`

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/bdg-formats#127]
https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L321

**Comment by heuermh** [comment]
To clarify, drop the `Contig` reference for a string `contigName` field?

**Comment by fnothaft** [comment]
> To clarify, drop the Contig reference for a string contigName field?

Yup!
