### ISSUE TITLE
Rename start/end fields in NucleotideContigFragment

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/bdg-formats#138]
All other "top level" records use start/end.

**Comment by heuermh** [comment]
Do you mean `fragmentStartPosition` &rarr; `fragmentStart` and `fragmentEndPosition` &rarr; `fragmentEnd`?

**Comment by fnothaft** [comment]
Nope, I meant `fragmentStartPosition` → `start` and `fragmentEndPosition` → `end`

**Comment by heuermh** [comment]
All the other fields start with `fragment` (which I dislike), so these should match for now.  I would like to replace `NucleotideContigFragment` with `Sequence` and `Slice` post bdg-formats version 0.11.0.

**Comment by fnothaft** [comment]
If we make this change, then we can support generated predicates on `NucleotideContigFragment` in https://github.com/bigdatagenomics/adam/pull/1540. Additionally, this is a small change that would harmonize the schemas. Anyways, it doesn't logically make sense to say "X improves Y but doesn't totally fix it, so let's not do X". Do you want me to drop the `fragment` prefixes from the other fields as well?

**Comment by heuermh** [comment]
Just made that suggestion in https://github.com/bigdatagenomics/bdg-formats/pull/139#issuecomment-303464145

**Comment by heuermh** [comment]
See #140

**Comment by fnothaft** [comment]
#140 sounds OK to me, but is realistically unrelated to #138, since we're not dropping `NucleotideContigFragment` in the immediate future.
