### ISSUE TITLE
ADAM Extension to precision medecine

### ISSUE THREAD

**Issue by fbelghait** [bigdatagenomics/bdg-formats#158]
Hello,

    I am working on a project to extend the ADAM Framework to precision medecines researches, I would like to open a project in ADAM for this initiative,  what is the process to follow.

Thank you

Fbelghait

**Comment by heuermh** [comment]
Hello @fbelghait, I would suggest starting a discussion about further schema changes on the ADAM Gitter at https://gitter.im/bigdatagenomics/adam.
