### ISSUE TITLE
Publish C/C++ artifacts

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/bdg-formats#22]
Publish the C/C++ artifacts, generated from the latest JSON (via bigdatagenomics.github.io?).

**Comment by heuermh** [comment]
Close as WontFix?

**Comment by fnothaft** [comment]
Let's keep this open. I've been doing a bit of thinking about the Python API, and we might need/want the JSON/AVDL schemas for that.

**Comment by heuermh** [comment]
Closing as WontFix
