### ISSUE TITLE
Re-organize the Feature schema

### ISSUE THREAD

**Issue by tdanford** [bigdatagenomics/bdg-formats#29]
This is a ticket to capture our collective thinking around the re-organization of the Feature schema.  The Feature schema needs to be edited to satisfy the following (additional) requirements: 

* it needs an explicit 'type' field
* it should be less file-format specific (i.e. fields like 'qValue' and 'signalValue' could be moved to an attributes field)
* we need to make sure it's as memory efficient as possible (and some benchmarking would be nice, too)

**Comment by laserson** [comment]
Closing in light of #30
