### ISSUE TITLE
Should `Genotype` allow for multiple `Variant`s / alleles?

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/bdg-formats#33]
@arahuja implied there had been some discussion around this in the past.

AFAICT there is no good way right now to capture there being two non-reference alleles at one locus, having [one `Variant` per `Genotype`](https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L510).

In the immediate term I will work around this by emitting two lines / `Variant`s in my VCFs, but I'm curious whether we should support the other way here. Thanks!

**Comment by heuermh** [comment]
Ping for an update.  Is there anything here to consider for #108?

**Comment by fnothaft** [comment]
I don't think there is. I'd be fine closing this.

**Comment by heuermh** [comment]
Closing as WontFix
