### ISSUE TITLE
AlignmentRecord not storing "TLEN" / "inferred insert size" from BAM

### ISSUE THREAD

**Issue by ryan-williams** [bigdatagenomics/bdg-formats#37]
I just noticed this field getting lost when converting into and out of BAMs with ADAM. Should we/I add it? Should we just infer it in ADAM? Or continue not supporting it?

See `TLEN` in the [SAM spec](http://samtools.github.io/hts-specs/SAMv1.pdf).

`htsjdk` puts it in `SAMRecord`s as ["inferred insert size"](https://github.com/samtools/htsjdk/blob/master/src/java/htsjdk/samtools/SAMRecord.java#L538)

**Comment by fnothaft** [comment]
Resolved by #50.
