### ISSUE TITLE
Rename Contig objects

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/bdg-formats#43]
I was writing code that munged `NucleotideContigFragment`s and realized that `Contig` should be changed to `Reference` and `NucleotideContigFragment` should be renamed to `Contig` or `ContigFragment`.

**Comment by laserson** [comment]
+1

**Comment by heuermh** [comment]
Consider also the renaming proposal in https://github.com/bigdatagenomics/adam/issues/997.

Perhaps
```
Contig -> Reference
new schema class ReferenceSet (or References, or Assembly, or SequenceDictionary, or ?)
new schema class Sequence
new schema class or enum Alphabet
NucleotideContigFragment -> SequenceFragment (or SequencePartition, or Slice, or ?)
```
