### ISSUE TITLE
Rename "end" fields

### ISSUE THREAD

**Issue by kozanitis** [bigdatagenomics/bdg-formats#49]
I have trouble accessing those "end" fields (e.g. AlignmentRecord.end, variant.end) with sparkSql because end is a reserved keyword there and it conflicts with the field names. 

I was wondering: Is it possible to assign different names to those fields?

**Comment by fnothaft** [comment]
Is there a way to escape the field names in Spark SQL? My preference would be against changing the `end` fields unless absolutely necessary.

**Comment by kozanitis** [comment]
No worries then... I just verified that you can escape column names using `end` (same convention as in HiveQL)

**Comment by slagelwa** [comment]
Encountered this myself recently, hence the reason we've been using "stop" instead of "end".  "stop" also seems to go along with "start" just a little more IMHO too.  Really wish SQL reserved keywords were taken into consideration.  Its a real pain to escape these in SQL statements...
