### ISSUE TITLE
Revisit VariantCallingAnnotations

### ISSUE THREAD

**Issue by arahuja** [bigdatagenomics/bdg-formats#57]
I wanted to revisit `VariantCallingAnnotations`.  It seems a lot of these fields are GATK specific and it seems hard to extend to add new annotations or variant calling output.

Might it make more sense to move of these to `attributes` and improve VCF output things from attributes (which it doesn't seem like it does currently?)

**Comment by arahuja** [comment]
Oh, just saw  #51 as well, but I would be in favor of dropping more of them perhaps?

**Comment by fnothaft** [comment]
I'm OK with dropping more, depending on which fields you want to drop. Beyond #51, what else do you think should be dropped?

**Comment by arahuja** [comment]
Yea, sorry @fnothaft that actually takes care of most of them, just hadn't seen it.

Is `usedForNegativeTrainingSet` that common?

**Comment by fnothaft** [comment]
@arahuja no worries! I don't think `usedForNegativeTrainingSet` is terribly common, so I am OK with dropping that as well. I'll do a bit further cleanup on #51 to drop that.

**Comment by fnothaft** [comment]
@arahuja I just made the cleanup you were requesting. Can you merge #51 if it looks good to you?
