### ISSUE TITLE
Add "fragmentEndPosition" field to NucleotideContigFragment

### ISSUE THREAD

**Issue by erictu** [bigdatagenomics/bdg-formats#71]
Currently we just have `fragmentStartPosition` and `fragmentLength`. To perform predicate filtering by a ReferenceRegion, we need a `fragmentEndPosition` field.

**Comment by heuermh** [comment]
Is this still the case?

**Comment by erictu** [comment]
Yes.

**Comment by heuermh** [comment]
Go ahead and pull request it then, I can add support to adam to populate it
