### ISSUE TITLE
I can't find Pileup class file in org.bdgenomics.formats.avro package.

### ISSUE THREAD

**Issue by xubo245** [bigdatagenomics/bdg-formats#74]
I can't find Pileup class file in org.bdgenomics.formats.avro package. than there is error:

val pileups = reads.adamRecords2Pileup().cache()
<console>:32: error: value adamRecords2Pileup is not a member of org.apache.spark.rdd.RDD[org.bdgenomics.formats.avro.AlignmentRecord]
       val pileups = reads.adamRecords2Pileup().cache()

Please how i can git the file and solute the error?

Thanks!

 
jack xu

@davidonlaptop @hammer @jey @massie @heuermh

**Comment by heuermh** [comment]
Hello @xubo245!

What versions of ADAM and bdg-formats are you using?  The Pileup command was removed from ADAM in this commit https://github.com/bigdatagenomics/adam/commit/3133df8f5eda13d264f6eb9f04b004ba1fabab9a.

**Comment by xubo245** [comment]
Thank you for your reply.I use Adam 0.19.0 and bdg-formats 0.72. I try to redo the project from http://ampcamp.berkeley.edu/5/exercises/genome-analysis-with-adam.html. Yesterday I try to build by maven but faild，now i am trying to build  Adam 0.14 again .

**Comment by fnothaft** [comment]
Closing as won't fix, as the `Pileup` model was removed a while back.
