### ISSUE TITLE
Add back dbSnp ID field

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/bdg-formats#96]
See discussion on https://github.com/bigdatagenomics/adam/issues/1103

**Comment by jpdna** [comment]
So one solution is to make 
https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L961
`union { null, int} dbsnp = null`
instead, so it acts as both a flag and a value.   Is that a good solution?

**Comment by jpdna** [comment]
Perhaps it is better to have an `ID` field in `VariantAnnotation` which is a string, that could capture whatever was in the ID field (3rd column) of the VCF field, and for dbSNP we would keep the "rs" prefix as that defines and accessioning space.

**Comment by fnothaft** [comment]
> Perhaps it is better to have an `ID` field in `VariantAnnotation` which is a string, that could capture whatever was in the ID field (3rd column) of the VCF field, and for dbSNP we would keep the "rs" prefix as that defines and accessioning space.

I would +1 that.

> Or - are we sure this should be in `VariantAnnotation` rather than a String field in `Variant`?

I personally like it more in `VariantAnnotation` but I can grok why it is a good fit in `Variant`. I'd love to hear other people's thoughts.

**Comment by heuermh** [comment]
Save it for tomorrow morning, guys.

:)
